version: '3'

services:
    app:
        build: .
        ports:
            - '3001:3001'
        command: node build/app.js
        environment:
            NODE_ENV: production
            PORT: 3001

            DB_HOST: host.docker.internal
            DB_USER: postgres
            DB_PASSWORD: postgres
            DB_DATABASE: kordy
            DB_PORT: 5432
