version: '3.2'

services:
    app:
        build: .
        container_name: kordy-api
        ports:
            - '3001:3001'
        command: node build/app.js
        env_file:
            - .env.example
        environment:
            DB_HOST: host.docker.internal
            AWS_S3_ENDPOINT: http://host.docker.internal:4566
