version: '3'

services:
    postgres:
        image: postgres:13-alpine
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: kordy

    app:
        build: .
        depends_on:
            - postgres
        ports:
            - '3001:3001'
        command: node build/app.js
        environment:
            NODE_ENV: production
            PORT: 3001
