version: '3.2'

services:
    localstack:
        image: localstack/localstack
        container_name: kordy-localstack
        ports:
            - '4566-4599:4566-4599'
            - '8080:8080'
        environment:
            - SERVICES=s3
            - DATA_DIR=/tmp/localstack/data
        volumes:
            - './.localstack/data:/tmp/localstack'
            - '/var/run/docker.sock:/var/run/docker.sock'
